base:
  seed: 77
  backbone: 'timm-efficientnet-b2'
  backbone_weight: 'noisy-student'
  model_arc: 'PAN'
  num_classes: 12
  image_size: 512
  output_dir: './results/'
  train_args:
    num_epochs: 20
    train_batch_size: 16
    max_lr: 0.001
    min_lr: 0.0001
    weight_decay: 0.0
    log_intervals: 10         
  val_args:    
    val_batch_size: 16

DeepLabV3Plus:
  seed: 77
  backbone: 'timm-efficientnet-b2'
  backbone_weight: 'imagenet'
  model_arc: 'DeepLabV3Plus'
  num_classes: 12
  image_size: 512
  output_dir: './results/'
  train_args:
    num_epochs: 30
    train_batch_size: 16
    max_lr: 0.001
    min_lr: 0.0001
    weight_decay: 0.0
    log_intervals: 10         
  val_args:    
    val_batch_size: 16

DeepLabV3Plus-b3:
  seed: 77
  backbone: 'timm-efficientnet-b3'
  backbone_weight: 'imagenet'
  model_arc: 'DeepLabV3Plus'
  num_classes: 12
  image_size: 512
  output_dir: './results/'
  train_args:
    num_epochs: 50
    train_batch_size: 10
    max_lr: 0.0001
    min_lr: 0.00001
    weight_decay: 0.0
    log_intervals: 10         
  val_args:    
    val_batch_size: 10


Light:
  seed: 77
  backbone: 'timm-efficientnet-b0'
  backbone_weight: 'imagenet'
  model_arc: 'UnetPlusPlus'
  image_size: 256
  num_classes: 12
  output_dir: './results/'
  train_args:
    num_epochs: 40
    train_batch_size: 64
    max_lr: 0.001
    min_lr: 0.0001
    weight_decay: 0.0
    log_intervals: 10
  val_args:    
    val_batch_size: 64


UNetPlusPlus:
  seed: 77
  backbone: 'timm-efficientnet-b3'
  backbone_weight: 'imagenet'
  model_arc: 'UnetPlusPlus'
  image_size: 512
  num_classes: 12
  output_dir: './results/'
  train_args:
    num_epochs: 50
    train_batch_size: 10
    max_lr: 0.001
    min_lr: 0.00005
    weight_decay: 0.0
    log_intervals: 10
  val_args:    
    val_batch_size: 10


DeepLabV3Plus-aux:
  seed: 77
  backbone: 'timm-efficientnet-b3'
  backbone_weight: 'imagenet'
  model_arc: 'DeepLabV3Plus'
  num_classes: 12
  image_size: 512
  output_dir: './results/'
  train_args:
    num_epochs: 40
    train_batch_size: 10
    max_lr: 0.001
    min_lr: 0.00005
    weight_decay: 0.0
    log_intervals: 10
  val_args:    
    val_batch_size: 10