base:
  seed: 2021
  backbone: 'timm-efficientnet-b3'
  backbone_weight: 'noisy-student'
  model_arc: 'PAN'
  num_classes: 12
  image_size: 512
  num_workers: 6
  output_dir: './results/'
  run_name : 'pan_base'
  optimizer: 'AdamW'
  criterion: 'TripleLoss'
  early_num: 4
  train_args:
    num_epochs: 10
    train_batch_size: 12
    max_lr: 0.0001
    min_lr: 0.00001
    weight_decay: 0.000001
  val_args:    
    val_batch_size: 12
  augmix_args:
    use_augmix: True
    augmix_prob: 0.5

Additional:
  seed: 2021
  backbone: 'timm-efficientnet-b3'
  backbone_weight: 'noisy-student'
  model_arc: 'PAN'
  num_classes: 12
  image_size: 512
  num_workers: 6
  output_dir: './results/'
  run_name : 'pan_base'
  optimizer: 'SGDW'
  criterion: 'TripleLoss'
  early_num: 4
  train_args:
    num_epochs: 3
    train_batch_size: 12
    max_lr: 0.0001
    min_lr: 0.00001
    weight_decay: 0.000001
  val_args:    
    val_batch_size: 12
  augmix_args:
    use_augmix: True
    augmix_prob: 0.5
    
madgrad:
  seed: 2021
  backbone: 'timm-efficientnet-b3'
  backbone_weight: 'noisy-student'
  model_arc: 'PAN'
  num_classes: 12
  image_size: 512
  num_workers: 2
  output_dir: './results/'
  run_name : 'pan_base'
  optimizer: 'MADGRAD'
  criterion: 'DiceFocalLoss'
  early_num: 4
  train_args:
    num_epochs: 30
    train_batch_size: 8
    max_lr: 0.0005
    min_lr: 0.00001
    weight_decay: 0
  val_args:    
    val_batch_size: 8
  augmix_args:
    use_augmix: True
    augmix_prob: 0.6
    
train_pseudo:
  seed: 2021
  backbone: 'timm-efficientnet-b3'
  backbone_weight: 'noisy-student'
  model_arc: 'PAN'
  num_classes: 12
  image_size: 512
  num_workers: 4
  output_dir: './results/'
  run_name : 'pan_base'
  first_optimizer: 'MADGRAD'
  second_optimizer : 'SGDW'
  criterion: 'TripleLoss'
  early_num: 10
  train_args:
    num_epochs: 35
    train_batch_size: 12
    max_lr: 0.0003
    min_lr: 0.00001
    weight_decay: 0.000001
  val_args:    
    val_batch_size: 12
  augmix_args:
    use_augmix: True
    augmix_prob: 0.7


train_pseudo_add:
  seed: 2021
  backbone: 'timm-efficientnet-b3'
  backbone_weight: 'noisy-student'
  model_arc: 'PAN'
  num_classes: 12
  image_size: 512
  num_workers: 4
  output_dir: './results/'
  run_name : 'pan_base'
  first_optimizer: 'MADGRAD'
  second_optimizer : 'SGDW'
  criterion: 'TripleLoss'
  early_num: 10
  train_args:
    num_epochs: 3
    train_batch_size: 12
    max_lr: 0.0005
    min_lr: 0.0001
    weight_decay: 0.000001
  val_args:    
    val_batch_size: 12
  augmix_args:
    use_augmix: True
    augmix_prob: 0.7