ensemble:
  seed: 2021
  backbone1: 'timm-efficientnet-b3'
  backbone2: 'timm-efficientnet-b3'
  model_arc1: 'PAN'
  model_arc2: 'UnetPlusPlus'
  image_size: 512
  num_classes: 12
  checkpoint1: 'final/best_mIoU.pth'
  checkpoint2: 'you/best_mIoU.pth'
  test_batch_size: 8
  

base:
  seed: 2021
  backbone: 'timm-efficientnet-b3'
  model_arc: 'PAN'
  image_size: 512
  num_classes: 12
  checkpoint: 'final/best_mIoU.pth'
  test_batch_size: 8
